### ISSUE TITLE
Add Microsemi PDC format output

### ISSUE THREAD

**Issue by CGrassin** [CGrassin/kicad-pinout-generator#3]
Support for Microsemi's Physical Design Constraint File (*.pdc file extension) for Libero SoC (for the following FPGA family: PolarFire, SmartFusion2, IGLOO2, RTG4, SmartFusion, IGLOO, ProASIC3, Fusion).

Sample:
```
set_io LED1 -pinname J16 -fixed yes -DIRECTION OUTPUT
```

**Comment by g0t00** [comment]
That seems to generally be implemented.
But for ProAsic 3 there seems to be a bogus pin to be detected.
```
set_io pin_ -pinname  -fixed yes
```
Also some power pins seem to be detected correctly and commented out, but some are not :(
